#!/bin/bash

USR=$1;
NODES=/commands/nodes;

if [ -z $USR ]; then
	echo "User name can not be empty...";
	exit;
fi

echo "Sending authorization token...";
for n in `cat $NODES | tail -n +3 | awk '{ print $1 }' | cut -d\. -f1`;
do 
        if [[ ${n:0:1} != "#" ]]; then
                echo "Node: $n";
                ssh-keyscan -H $n >> /home/$USR/.ssh/known_hosts;
		ssh-keyscan -H $n.arun-hpcc.ru.ac.bd >> /home/$USR/.ssh/known_hosts;
        fi; 
done;
ssh-keyscan -H master >> /home/$USR/.ssh/known_hosts;
ssh-keyscan -H master.arun-hpcc.ru.ac.bd >> /home/$USR/.ssh/known_hosts;
chown $USR:$USR /home/$USR/.ssh/known_hosts;
chmod 644 /home/$USR/.ssh/known_hosts;
echo "Authorization Updated";
echo "Done";

exit
